### ISSUE TITLE
how to convert .vtk to .annot file?

### ISSUE THREAD

**Issue by tanjia123456** [binarybottle/mindboggle_sidelined#1]
Hello, I use freesurfer software, and download the surfacelabel in mindboggle.
I have .vtk file, But I want to convert it to .annot file to visualize. If you know please give me an example.

**Comment by binarybottle** [comment]
The mindboggle python library has a function to go the other way:
https://mindboggle.readthedocs.io/en/latest/api/mindboggle.mio.html?highlight=.annot#mindboggle.mio.vtks.freesurfer_annot_to_vtk

You would have to check FreeSurfer to see if they have any function to go from vtk ascii to annot files.
